<?php

namespace app\models;

class User extends UsersBase
{
    public $password;

    public function rules()
    {
        return array_merge([
            ['password', 'string', 'min'=>6],
            ['email', 'email'],
            ['email', 'unique']
        ]); parent::rules(); // TODO: Change the autogenerated stub
    }

}
